# Generated by Django 3.2.7 on 2021-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_food_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_prepaerd', models.BooleanField(default=False)),
                ('dateTime', models.DateTimeField()),
                ('discount', models.IntegerField()),
                ('total_order_price', models.IntegerField()),
                ('transport_cost', models.IntegerField()),
                ('packaging_cost', models.IntegerField()),
            ],
        ),
    ]
